server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: false